// Generated by gencpp from file robot_sim/other_taskRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_SIM_MESSAGE_OTHER_TASKREQUEST_H
#define ROBOT_SIM_MESSAGE_OTHER_TASKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_sim
{
template <class ContainerAllocator>
struct other_taskRequest_
{
  typedef other_taskRequest_<ContainerAllocator> Type;

  other_taskRequest_()
    : task_data(0)
    , task_type()
    , task_id(0)  {
    }
  other_taskRequest_(const ContainerAllocator& _alloc)
    : task_data(0)
    , task_type(_alloc)
    , task_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _task_data_type;
  _task_data_type task_data;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _task_type_type;
  _task_type_type task_type;

   typedef int64_t _task_id_type;
  _task_id_type task_id;





  typedef boost::shared_ptr< ::robot_sim::other_taskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_sim::other_taskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct other_taskRequest_

typedef ::robot_sim::other_taskRequest_<std::allocator<void> > other_taskRequest;

typedef boost::shared_ptr< ::robot_sim::other_taskRequest > other_taskRequestPtr;
typedef boost::shared_ptr< ::robot_sim::other_taskRequest const> other_taskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_sim::other_taskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_sim::other_taskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_sim

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robot_sim': ['/home/hcappel1/Multi_Agent_Systems/src/robot_sim/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_sim::other_taskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_sim::other_taskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_sim::other_taskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_sim::other_taskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_sim::other_taskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_sim::other_taskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_sim::other_taskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0f539cb3e5e23bc53002dc7b1f24555";
  }

  static const char* value(const ::robot_sim::other_taskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0f539cb3e5e23bcULL;
  static const uint64_t static_value2 = 0x53002dc7b1f24555ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_sim::other_taskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_sim/other_taskRequest";
  }

  static const char* value(const ::robot_sim::other_taskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_sim::other_taskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 task_data\n\
string task_type\n\
int64 task_id\n\
\n\
";
  }

  static const char* value(const ::robot_sim::other_taskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_sim::other_taskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_data);
      stream.next(m.task_type);
      stream.next(m.task_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct other_taskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_sim::other_taskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_sim::other_taskRequest_<ContainerAllocator>& v)
  {
    s << indent << "task_data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.task_data);
    s << indent << "task_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.task_type);
    s << indent << "task_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.task_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SIM_MESSAGE_OTHER_TASKREQUEST_H
