// Generated by gencpp from file robot_sim/planner.msg
// DO NOT EDIT!


#ifndef ROBOT_SIM_MESSAGE_PLANNER_H
#define ROBOT_SIM_MESSAGE_PLANNER_H

#include <ros/service_traits.h>


#include <robot_sim/plannerRequest.h>
#include <robot_sim/plannerResponse.h>


namespace robot_sim
{

struct planner
{

typedef plannerRequest Request;
typedef plannerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct planner
} // namespace robot_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_sim::planner > {
  static const char* value()
  {
    return "6423f791599f0a66e62771c89cda1dcd";
  }

  static const char* value(const ::robot_sim::planner&) { return value(); }
};

template<>
struct DataType< ::robot_sim::planner > {
  static const char* value()
  {
    return "robot_sim/planner";
  }

  static const char* value(const ::robot_sim::planner&) { return value(); }
};


// service_traits::MD5Sum< ::robot_sim::plannerRequest> should match 
// service_traits::MD5Sum< ::robot_sim::planner > 
template<>
struct MD5Sum< ::robot_sim::plannerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_sim::planner >::value();
  }
  static const char* value(const ::robot_sim::plannerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_sim::plannerRequest> should match 
// service_traits::DataType< ::robot_sim::planner > 
template<>
struct DataType< ::robot_sim::plannerRequest>
{
  static const char* value()
  {
    return DataType< ::robot_sim::planner >::value();
  }
  static const char* value(const ::robot_sim::plannerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_sim::plannerResponse> should match 
// service_traits::MD5Sum< ::robot_sim::planner > 
template<>
struct MD5Sum< ::robot_sim::plannerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_sim::planner >::value();
  }
  static const char* value(const ::robot_sim::plannerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_sim::plannerResponse> should match 
// service_traits::DataType< ::robot_sim::planner > 
template<>
struct DataType< ::robot_sim::plannerResponse>
{
  static const char* value()
  {
    return DataType< ::robot_sim::planner >::value();
  }
  static const char* value(const ::robot_sim::plannerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SIM_MESSAGE_PLANNER_H
