// Generated by gencpp from file robot_sim/plannerRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_SIM_MESSAGE_PLANNERREQUEST_H
#define ROBOT_SIM_MESSAGE_PLANNERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_sim
{
template <class ContainerAllocator>
struct plannerRequest_
{
  typedef plannerRequest_<ContainerAllocator> Type;

  plannerRequest_()
    : coords_msg()  {
    }
  plannerRequest_(const ContainerAllocator& _alloc)
    : coords_msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _coords_msg_type;
  _coords_msg_type coords_msg;





  typedef boost::shared_ptr< ::robot_sim::plannerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_sim::plannerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct plannerRequest_

typedef ::robot_sim::plannerRequest_<std::allocator<void> > plannerRequest;

typedef boost::shared_ptr< ::robot_sim::plannerRequest > plannerRequestPtr;
typedef boost::shared_ptr< ::robot_sim::plannerRequest const> plannerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_sim::plannerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_sim::plannerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_sim

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robot_sim': ['/home/hcappel1/Multi_Agent_Systems/src/robot_sim/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_sim::plannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_sim::plannerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_sim::plannerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_sim::plannerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_sim::plannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_sim::plannerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_sim::plannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa571bd3d8279217f2fb0b2475d614e2";
  }

  static const char* value(const ::robot_sim::plannerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa571bd3d8279217ULL;
  static const uint64_t static_value2 = 0xf2fb0b2475d614e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_sim::plannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_sim/plannerRequest";
  }

  static const char* value(const ::robot_sim::plannerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_sim::plannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] coords_msg\n\
";
  }

  static const char* value(const ::robot_sim::plannerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_sim::plannerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.coords_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct plannerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_sim::plannerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_sim::plannerRequest_<ContainerAllocator>& v)
  {
    s << indent << "coords_msg[]" << std::endl;
    for (size_t i = 0; i < v.coords_msg.size(); ++i)
    {
      s << indent << "  coords_msg[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.coords_msg[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SIM_MESSAGE_PLANNERREQUEST_H
