// Generated by gencpp from file robot_sim/pos_task.msg
// DO NOT EDIT!


#ifndef ROBOT_SIM_MESSAGE_POS_TASK_H
#define ROBOT_SIM_MESSAGE_POS_TASK_H

#include <ros/service_traits.h>


#include <robot_sim/pos_taskRequest.h>
#include <robot_sim/pos_taskResponse.h>


namespace robot_sim
{

struct pos_task
{

typedef pos_taskRequest Request;
typedef pos_taskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pos_task
} // namespace robot_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_sim::pos_task > {
  static const char* value()
  {
    return "1998cd4f5d6808303435266496f15d7e";
  }

  static const char* value(const ::robot_sim::pos_task&) { return value(); }
};

template<>
struct DataType< ::robot_sim::pos_task > {
  static const char* value()
  {
    return "robot_sim/pos_task";
  }

  static const char* value(const ::robot_sim::pos_task&) { return value(); }
};


// service_traits::MD5Sum< ::robot_sim::pos_taskRequest> should match 
// service_traits::MD5Sum< ::robot_sim::pos_task > 
template<>
struct MD5Sum< ::robot_sim::pos_taskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_sim::pos_task >::value();
  }
  static const char* value(const ::robot_sim::pos_taskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_sim::pos_taskRequest> should match 
// service_traits::DataType< ::robot_sim::pos_task > 
template<>
struct DataType< ::robot_sim::pos_taskRequest>
{
  static const char* value()
  {
    return DataType< ::robot_sim::pos_task >::value();
  }
  static const char* value(const ::robot_sim::pos_taskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_sim::pos_taskResponse> should match 
// service_traits::MD5Sum< ::robot_sim::pos_task > 
template<>
struct MD5Sum< ::robot_sim::pos_taskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_sim::pos_task >::value();
  }
  static const char* value(const ::robot_sim::pos_taskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_sim::pos_taskResponse> should match 
// service_traits::DataType< ::robot_sim::pos_task > 
template<>
struct DataType< ::robot_sim::pos_taskResponse>
{
  static const char* value()
  {
    return DataType< ::robot_sim::pos_task >::value();
  }
  static const char* value(const ::robot_sim::pos_taskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SIM_MESSAGE_POS_TASK_H
